// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-forms/AmbientProof.tsx": () => import("../components/mockups/login-forms/AmbientProof.tsx"),
  "./components/mockups/login-forms/Industrial.tsx": () => import("../components/mockups/login-forms/Industrial.tsx"),
  "./components/mockups/login-forms/SplitScreen.tsx": () => import("../components/mockups/login-forms/SplitScreen.tsx")
};
